export const profile = {
  name: "KRISHNA KUMAR",
  role: "SOFTWARE ENGINEER",
  email: "meet.kumarkrishna@gmail.com",
  github: "https://github.com/Krishnaqwerty",
  githubUser: "Krishnaqwerty",
  githubReposUrl: "https://github.com/Krishnaqwerty?tab=repositories",
  linkedin: "https://www.linkedin.com/in/krishnaqwerty/",
  medium: "https://krishnaqwerty.medium.com/",
  resumePath: "/KrishnaKumar.pdf",
  summary:
    "Full-stack and Android developer focused on building scalable, user-centric products.",
  stack: [
    "Next.js",
    "React",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Express",
    "Python",
    "AI/ML",
    "Kotlin",
    "Java",
    "Android",
    "Tailwind CSS",
    "PostgreSQL",
    "MongoDB",
    "REST/GraphQL",
    "Docker",
    "Git",
  ],
  hobbies: ["Yoga", "Astrology", "Space Science", "Biology", "Research orientation"],
  techBadges: ["Next.js", "TypeScript", "Node.js"],
  socialLinks: [
    { href: "mailto:meet.kumarkrishna@gmail.com", label: "Email" },
    { href: "https://github.com/Krishnaqwerty", label: "GitHub" },
    { href: "https://www.linkedin.com/in/krishnaqwerty/", label: "LinkedIn" },
    { href: "https://krishnaqwerty.medium.com/", label: "Medium" },
  ],
};